import Head from "next/head";
import Link from "next/link";
import { Card, Dialog } from "@radix-ui/themes";


import { api } from "~/utils/api";
import { useState } from "react";

export default function IssuesPage() {
  const { data, fetchNextPage } = api.issue.getIssues.useInfiniteQuery({
      limit: 10,
    },
    {
      getNextPageParam: (lastPage) => {
        lastPage.nextCursor;
        if (lastPage.nextCursor) {
          return lastPage.nextCursor;
        }
        return undefined;
      },
    }
  );

  const [page, setPage] = useState(0);
  const issues = data?.pages[page]?.items;

  return (
    <>
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        <div className="container flex flex-col items-center justify-center gap-2 px-4 py-16 ">
          {issues?.map(issue => 
            <Card key={issue.id} size="4" asChild className="w-3/5">
              <Link className="hover:border-blue-600"
                href={`/issues/${issue.id}`}
              >
                <h2 className="text-lg font-bold">{issue.title}</h2>
                <p>{issue.description}</p>
              </Link>
            </Card> 
          )}
          <div className="flex flex-row aling-middle justify-center">
            <button className=" px-2 py-1 m-2 bg-gray-200 rounded flex-auto"
              onClick={() => {
                setPage(page => page - 1);
              }}
              >
                {"<"}
            </button>
            <button className=" px-2 py-1 m-2 bg-gray-200 rounded flex-auto"
              onClick={() => {
                // eslint-disable-next-line @typescript-eslint/no-floating-promises
                fetchNextPage();
                setPage(page => page + 1);
              }}
              >
              {">"}
            </button>
          </div>
        </div>

      </main>
    </>
  );
}
